#notifications:
#  recipients:
#    - groonga-commit@lists.sourceforge.jp
#    - travis@clear-code.com
language: node_js
node_js:
 - 0.6
 - 0.8
env:
 - GROONGA_MASTER=yes
install:
 - curl https://raw.github.com/groonga/groonga/master/data/travis/setup.sh | sh
 - npm install
 - npm install git://github.com/groonga/gcs.git
script: npm test
